const Movies = [
    {posterUrl: "https://images.affiches-et-posters.com//albums/3/3545/medium/3545-affiche-officielle-film-the-expendables-2.jpg",
    title: "EXPENDABLES 2",
    description: "film d'action",
    rate: 7/10,
   },
    {posterUrl:"https://images.affiches-et-posters.com//albums/3/4279/medium/4279-affiche-film-good-morning-england.jpg",
    title: "Good morning ENGLAND",
    description: "film romantique",
    rate: 4/10,
    },
    {posterUrl:"https://images.affiches-et-posters.com//albums/3/56158/medium/affiche-film-belle-epoque.jpg",
     title: "La belle époque",
     description: "film d'amour",
     rate: 4/10,
    },
    {posterUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSYnYPvLAOyQ5r6hbW9lmIBPfGsQskzXMOaAmnOHCpb&s",
    title: "Revanche",
    description: "film policier",
    rate: 9/10,
    },
]
export default Movies;